spring:
  datasource:
    url: jdbc:mysql://localhost:3306/integrixflowbridge?useSSL=false&serverTimezone=UTC
    username: root
    password: B3st3r@01
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
